module.exports = {
  TESTS: "/tests",
  TEST_ID: "/test/:id",
  EDIT_TEST_ID: "/test/edit/:id",
  LOGIN: "/login",
  REFRESH: "/refresh",
  LOGOUT: "/logout",
  USERS: "/users",
  USER_ID: "/user/:id",
  EDIT_USER_ID: "/user/edit/:id",
  UPDATE_PASSWORD: "/updatePassword/:id",
  PRODUCTS: "/products",
  PRODUCT_ID: "/product/:id",
  EDIT_PRODUCT_ID: "/product/edit/:id",
  TRANSACTIONS: "/transactions",
  TRANSACTION_ID: "/transaction/:id",
  EDIT_TRANSACTION_ID: "/transaction/edit/:id",
};
